import {test} from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import {randomUUID} from 'node:crypto';

test('wallet/event accounting and external REST/MCP authentication isolation',async t=>{
  const dir=mkdtempSync(join(tmpdir(),'dgc-wallet-test-'));
  const path=join(dir,'test.sqlite'),port=18793;
  const server=spawn(process.execPath,['src/server.js'],{env:{...process.env,DATABASE_PATH:path,PORT:String(port),TELEGRAM_BOT_TOKEN:''},stdio:'pipe'});
  let logs='';server.stderr.on('data',data=>logs+=data);server.stdout.on('data',data=>logs+=data);
  let db;
  t.after(async()=>{db?.close();server.kill();await new Promise(resolve=>server.exitCode!==null?resolve():server.once('exit',resolve));rmSync(dir,{recursive:true,force:true});});
  for(let i=0;i<100;i++){try{if((await fetch('http://127.0.0.1:'+port+'/api/health')).ok)break;}catch{}await new Promise(r=>setTimeout(r,30));if(i===99)throw new Error(logs);}
  db=new DatabaseSync(path);db.exec('PRAGMA busy_timeout=5000');
  for(const [id,role] of [['admin','ADMIN'],['staff','USER'],['alice','USER'],['bob','USER'],['other','USER']]){
    db.prepare('INSERT INTO users(id,username,balance,created_at,role) VALUES(?,?,1000,?,?)').run(id,id,new Date().toISOString(),role);
    db.prepare('INSERT INTO sessions VALUES(?,?,?)').run('test-'+id,id,new Date(Date.now()+3600000).toISOString());
  }
  const call=async(user,path,body)=>{const r=await fetch('http://127.0.0.1:'+port+path,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json',cookie:'dg_session=test-'+user},body:body===undefined?undefined:JSON.stringify(body)});return {status:r.status,...await r.json()};};
  const balance=id=>db.prepare('SELECT balance FROM users WHERE id=?').get(id).balance;
  const total=()=>db.prepare('SELECT SUM(balance) n FROM users').get().n+db.prepare("SELECT balance FROM system_accounts WHERE name='HOUSE'").get().balance;
  const initial=total();
  assert.equal((await call('unknown','/api/wallet')).status,401);
  const crossSite=await fetch('http://127.0.0.1:'+port+'/api/wallet/send',{method:'POST',headers:{cookie:'dg_session=test-alice','Content-Type':'text/plain'},body:'{}'});
  assert.equal(crossSite.status,403);
  const payment={recipientId:'bob',amount:125,note:'Lunch',requestKey:randomUUID()};
  const responses=await Promise.all([call('alice','/api/wallet/send',payment),call('alice','/api/wallet/send',payment)]);
  assert.ok(responses.every(r=>r.status===200));assert.equal(balance('alice'),875);assert.equal(balance('bob'),1125);
  assert.equal((await call('alice','/api/wallet/send',{...payment,amount:126})).status,400);
  for(const amount of [-1,0,0.001,1001,'10'])assert.equal((await call('alice','/api/wallet/send',{...payment,amount,requestKey:randomUUID()})).status,400);
  assert.equal((await call('alice','/api/wallet/send',{...payment,recipientId:'alice',requestKey:randomUUID()})).status,400);
  const concurrent=await Promise.all([1,2].map(()=>call('other','/api/wallet/send',{recipientId:'bob',amount:700,requestKey:randomUUID()})));
  assert.equal(concurrent.filter(r=>r.status===200).length,1);assert.equal(balance('other'),300);
  const config={name:'Guild test',description:'Participation',startsAt:new Date(Date.now()-60000).toISOString(),endsAt:new Date(Date.now()+3600000).toISOString(),reward:25,entryCost:100,budget:50,active:true};
  assert.equal((await call('staff','/api/events',config)).status,403);
  const created=await call('admin','/api/events',config);assert.equal(created.status,200);const id=created.event.id,base='/api/events/'+id;
  assert.equal((await call('staff',base+'/grant',{userId:'alice'})).status,403);
  assert.equal((await call('alice',base+'/staff',{userId:'alice',canGrant:true,limit:999})).status,403);
  assert.equal((await call('admin',base+'/staff',{userId:'staff',canGrant:true,canRedeem:true,limit:25})).status,200);
  assert.equal((await call('staff',base+'/grant',{userId:'staff'})).status,400);
  assert.equal((await call('staff',base+'/grant',{userId:'alice'})).status,200);
  assert.equal((await call('staff',base+'/grant',{userId:'alice'})).alreadyProcessed,true);
  assert.equal(balance('alice'),900);
  assert.equal((await call('staff',base+'/grant',{userId:'bob'})).status,400);
  assert.equal((await call('admin',base+'/grant',{userId:'bob'})).status,200);
  assert.equal((await call('admin',base+'/grant',{userId:'other'})).status,400);
  assert.equal((await call('admin','/api/events',{...config,id,budget:25})).status,400);
  assert.equal((await call('admin',base+'/staff',{userId:'staff',canGrant:true,limit:0})).status,400);
  let pass=await call('alice',base+'/entry-token',{});assert.equal(pass.status,200);assert.equal(balance('alice'),900);
  assert.equal((await call('bob',base+'/checkin',{token:pass.token})).status,403);
  assert.equal((await call('bob',base+'/entry-preview',{token:pass.token})).status,403);
  assert.equal((await call('staff',base+'/entry-preview',{token:pass.token})).username,'alice');
  assert.equal((await call('staff',base+'/checkin',{token:pass.token})).status,200);
  assert.equal((await call('staff',base+'/checkin',{token:pass.token})).alreadyProcessed,true);
  assert.equal((await call('staff',base+'/entry-preview',{token:pass.token})).status,400);
  assert.equal(balance('alice'),800);assert.equal((await call('alice',base+'/entry-token',{})).status,400);
  pass=await call('bob',base+'/entry-token',{});
  db.prepare('UPDATE entry_tokens SET expires_at=? WHERE token=?').run('2020-01-01T00:00:00.000Z',pass.token);
  assert.equal((await call('staff',base+'/checkin',{token:pass.token})).status,400);
  pass=await call('bob',base+'/entry-token',{});
  await call('admin','/api/events',{...config,id,entryCost:150});
  assert.equal((await call('staff',base+'/checkin',{token:pass.token})).status,400);
  pass=await call('bob',base+'/entry-token',{});
  await call('admin',base+'/staff',{userId:'staff',canGrant:false,canRedeem:false,limit:25});
  assert.equal((await call('staff',base+'/checkin',{token:pass.token})).status,403);
  assert.equal((await call('staff',base+'/history')).status,403);
  assert.equal((await call('admin',base+'/checkin',{token:pass.token})).status,200);
  pass=await call('other',base+'/entry-token',{});
  await call('other','/api/wallet/send',{recipientId:'bob',amount:250,requestKey:randomUUID()});
  assert.equal((await call('admin',base+'/checkin',{token:pass.token})).status,400);
  assert.equal(balance('other'),50);
  await call('admin','/api/events',{...config,id,active:false});
  assert.equal((await call('other',base+'/entry-token',{})).status,400);
  assert.equal(total(),initial,'all DGC conserved between users and treasury');
  assert.equal(db.prepare('SELECT COUNT(*) n FROM wallet_transfers').get().n,3);
  assert.equal(db.prepare('SELECT COUNT(*) n FROM event_claims').get().n,4);
  assert.equal(db.prepare("SELECT COUNT(*) n FROM audit_log WHERE event_type='WALLET_TRANSFER'").get().n,3);
  assert.equal(db.prepare("SELECT SUM(amount) n FROM ledger").get().n+db.prepare('SELECT SUM(amount) n FROM house_ledger').get().n,0);
  // External REST/MCP must never inherit browser sessions or confer write access.
  db.prepare('UPDATE users SET telegram_id=? WHERE id=?').run('test-telegram-alice','alice');
  const seeded=await call('alice','/api/markets',{question:'Will the API tests pass?',description:'Resolves yes when the isolated integration tests pass.',closesAt:new Date(Date.now()+86400000).toISOString(),openingOutcome:'YES'});
  assert.equal(seeded.status,201);
  const external=async(path,{token,method='GET',body,headers={}}={})=>{
    const r=await fetch('http://127.0.0.1:'+port+path,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{}),...headers},body:body===undefined?undefined:JSON.stringify(body)});
    return {status:r.status,data:r.status===202||r.status===204?null:await r.json()};
  };
  assert.equal((await external('/api/v1/stats')).status,200);
  assert.equal((await external('/api/v1/openapi.json')).data.openapi,'3.1.0');
  const listed=await external('/api/v1/markets?limit=1',{headers:{cookie:'dg_session=test-alice'}});
  assert.equal(listed.data.markets.items.length,1);assert.deepEqual(listed.data.markets.items[0].positions,{});
  const slug=listed.data.markets.items[0].slug;
  assert.equal((await external('/api/v1/markets/'+slug)).data.market.question,'Will the API tests pass?');
  const chart=await external('/api/v1/markets/'+slug+'/history?limit=1&offset=1');
  assert.equal(chart.data.history.items.length,1);assert.equal(chart.data.history.offset,1);
  assert.equal((await external('/api/v1/markets/missing')).status,404);
  assert.equal((await external('/api/v1/profiles/alice')).data.user.username,'alice');
  assert.equal((await external('/api/v1/leaderboard')).data.users.length,1);
  assert.equal((await external('/api/v1/me',{headers:{cookie:'dg_session=test-alice'}})).status,401);
  assert.equal((await external('/api/v1/markets?limit=101')).status,400);
  assert.equal((await external('/api/v1/markets?sort=evil')).status,400);
  assert.equal((await external('/api/v1/me',{token:'garbage'})).status,401);
  assert.equal((await call('unknown','/api/developer/tokens',{name:'client',scopes:['account:read'],days:30})).status,401);
  assert.equal((await call('alice','/api/developer/tokens',{name:'client',scopes:['admin'],days:30})).status,400);
  const issued=await call('alice','/api/developer/tokens',{name:'test client',scopes:['account:read'],days:7});
  assert.equal(issued.status,201);assert.ok(issued.token.startsWith('dgc_'));
  assert.equal((await external('/api/v1/me',{token:issued.token})).data.user.id,'alice');
  assert.equal((await external('/api/v1/me?user=bob',{token:issued.token})).status,400);
  assert.equal((await external('/api/v1/me/wallet',{token:issued.token})).status,403);
  assert.equal((await external('/api/v1/markets',{token:issued.token,method:'POST',body:{}})).status,405);
  assert.equal((await external('/api/wallet/send',{token:issued.token,method:'POST',body:{recipientId:'bob',amount:1,requestKey:randomUUID()}})).status,401);
  const tokenList=await call('alice','/api/developer/tokens');assert.ok(!JSON.stringify(tokenList).includes(issued.token));
  const stored=db.prepare('SELECT token_hash FROM api_tokens WHERE id=?').get(issued.id);assert.notEqual(stored.token_hash,issued.token);
  const mcp=async(method,args={},token,headers={})=>external('/mcp',{token,method:'POST',headers:{Accept:'application/json, text/event-stream',...headers},body:{jsonrpc:'2.0',id:1,method,params:args}});
  assert.equal((await mcp('initialize',{protocolVersion:'2025-06-18',clientInfo:{name:'test',version:'1'},capabilities:{}})).data.result.protocolVersion,'2025-06-18');
  assert.equal((await mcp('tools/list')).data.result.tools.length,6);
  assert.equal((await mcp('tools/list',{},issued.token)).data.result.tools.length,7);
  assert.equal((await mcp('tools/call',{name:'get_my_account'},issued.token)).data.result.structuredContent.user.id,'alice');
  assert.equal((await mcp('tools/call',{name:'get_my_account'})).data.result.isError,true);
  assert.equal((await mcp('tools/call',{name:'get_stats'})).data.result.isError,false);
  assert.equal((await mcp('tools/call',{name:'get_stats',arguments:{inject:'x'}})).data.result.isError,true);
  assert.equal((await mcp('tools/list',{},undefined,{Origin:'https://evil.example'})).status,403);
  assert.equal((await mcp('tools/list',{},undefined,{'MCP-Protocol-Version':'nope'})).status,400);
  assert.equal((await external('/mcp')).status,405);
  assert.equal((await external('/mcp',{method:'POST',headers:{Accept:'application/json, text/event-stream'},body:{jsonrpc:'2.0',method:'notifications/initialized'}})).status,202);
  assert.equal((await external('/api/developer/tokens/'+issued.id,{method:'DELETE',headers:{cookie:'dg_session=test-bob'},body:{}})).status,404);
  assert.equal((await external('/api/developer/tokens/'+issued.id,{method:'DELETE',headers:{cookie:'dg_session=test-alice'},body:{}})).status,200);
  assert.equal((await external('/api/v1/me',{token:issued.token})).status,401);
  assert.equal((await mcp('tools/list',{},issued.token)).status,401);
  const walletToken=await call('bob','/api/developer/tokens',{name:'wallet client',scopes:['wallet:read'],days:30});
  assert.equal((await external('/api/v1/me/wallet',{token:walletToken.token})).data.balance,balance('bob'));
  assert.equal((await external('/api/v1/me',{token:walletToken.token})).status,403);
  db.prepare('UPDATE api_tokens SET expires_at=? WHERE id=?').run('2020-01-01',walletToken.id);
  assert.equal((await external('/api/v1/me/wallet',{token:walletToken.token})).status,401);
});
