import {test} from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import {randomUUID} from 'node:crypto';

test('wallet and event accounting, permissions and replay safety',async t=>{
  const dir=mkdtempSync(join(tmpdir(),'dgc-wallet-test-'));
  const path=join(dir,'test.sqlite'),port=18793;
  const server=spawn(process.execPath,['src/server.js'],{env:{...process.env,DATABASE_PATH:path,PORT:String(port),TELEGRAM_BOT_TOKEN:''},stdio:'pipe'});
  let logs='';server.stderr.on('data',data=>logs+=data);server.stdout.on('data',data=>logs+=data);
  let db;
  t.after(async()=>{db?.close();server.kill();await new Promise(resolve=>server.exitCode!==null?resolve():server.once('exit',resolve));rmSync(dir,{recursive:true,force:true});});
  for(let i=0;i<100;i++){try{if((await fetch('http://127.0.0.1:'+port+'/api/health')).ok)break;}catch{}await new Promise(r=>setTimeout(r,30));if(i===99)throw new Error(logs);}
  db=new DatabaseSync(path);db.exec('PRAGMA busy_timeout=5000');
  for(const [id,role] of [['admin','ADMIN'],['staff','USER'],['alice','USER'],['bob','USER'],['other','USER']]){
    db.prepare('INSERT INTO users(id,username,balance,created_at,role) VALUES(?,?,1000,?,?)').run(id,id,new Date().toISOString(),role);
    db.prepare('INSERT INTO sessions VALUES(?,?,?)').run('test-'+id,id,new Date(Date.now()+3600000).toISOString());
  }
  const call=async(user,path,body)=>{const r=await fetch('http://127.0.0.1:'+port+path,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json',cookie:'dg_session=test-'+user},body:body===undefined?undefined:JSON.stringify(body)});return {status:r.status,...await r.json()};};
  const balance=id=>db.prepare('SELECT balance FROM users WHERE id=?').get(id).balance;
  const total=()=>db.prepare('SELECT SUM(balance) n FROM users').get().n+db.prepare("SELECT balance FROM system_accounts WHERE name='HOUSE'").get().balance;
  const initial=total();
  assert.equal((await call('unknown','/api/wallet')).status,401);
  const crossSite=await fetch('http://127.0.0.1:'+port+'/api/wallet/send',{method:'POST',headers:{cookie:'dg_session=test-alice','Content-Type':'text/plain'},body:'{}'});
  assert.equal(crossSite.status,403);
  const payment={recipientId:'bob',amount:125,note:'Lunch',requestKey:randomUUID()};
  const responses=await Promise.all([call('alice','/api/wallet/send',payment),call('alice','/api/wallet/send',payment)]);
  assert.ok(responses.every(r=>r.status===200));assert.equal(balance('alice'),875);assert.equal(balance('bob'),1125);
  assert.equal((await call('alice','/api/wallet/send',{...payment,amount:126})).status,400);
  for(const amount of [-1,0,0.001,1001,'10'])assert.equal((await call('alice','/api/wallet/send',{...payment,amount,requestKey:randomUUID()})).status,400);
  assert.equal((await call('alice','/api/wallet/send',{...payment,recipientId:'alice',requestKey:randomUUID()})).status,400);
  const concurrent=await Promise.all([1,2].map(()=>call('other','/api/wallet/send',{recipientId:'bob',amount:700,requestKey:randomUUID()})));
  assert.equal(concurrent.filter(r=>r.status===200).length,1);assert.equal(balance('other'),300);
  const config={name:'Guild test',description:'Participation',startsAt:new Date(Date.now()-60000).toISOString(),endsAt:new Date(Date.now()+3600000).toISOString(),reward:25,entryCost:100,budget:50,active:true};
  assert.equal((await call('staff','/api/events',config)).status,403);
  const created=await call('admin','/api/events',config);assert.equal(created.status,200);const id=created.event.id,base='/api/events/'+id;
  assert.equal((await call('staff',base+'/grant',{userId:'alice'})).status,403);
  assert.equal((await call('alice',base+'/staff',{userId:'alice',canGrant:true,limit:999})).status,403);
  assert.equal((await call('admin',base+'/staff',{userId:'staff',canGrant:true,canRedeem:true,limit:25})).status,200);
  assert.equal((await call('staff',base+'/grant',{userId:'staff'})).status,400);
  assert.equal((await call('staff',base+'/grant',{userId:'alice'})).status,200);
  assert.equal((await call('staff',base+'/grant',{userId:'alice'})).alreadyProcessed,true);
  assert.equal(balance('alice'),900);
  assert.equal((await call('staff',base+'/grant',{userId:'bob'})).status,400);
  assert.equal((await call('admin',base+'/grant',{userId:'bob'})).status,200);
  assert.equal((await call('admin',base+'/grant',{userId:'other'})).status,400);
  assert.equal((await call('admin','/api/events',{...config,id,budget:25})).status,400);
  assert.equal((await call('admin',base+'/staff',{userId:'staff',canGrant:true,limit:0})).status,400);
  let pass=await call('alice',base+'/entry-token',{});assert.equal(pass.status,200);assert.equal(balance('alice'),900);
  assert.equal((await call('bob',base+'/checkin',{token:pass.token})).status,403);
  assert.equal((await call('bob',base+'/entry-preview',{token:pass.token})).status,403);
  assert.equal((await call('staff',base+'/entry-preview',{token:pass.token})).username,'alice');
  assert.equal((await call('staff',base+'/checkin',{token:pass.token})).status,200);
  assert.equal((await call('staff',base+'/checkin',{token:pass.token})).alreadyProcessed,true);
  assert.equal((await call('staff',base+'/entry-preview',{token:pass.token})).status,400);
  assert.equal(balance('alice'),800);assert.equal((await call('alice',base+'/entry-token',{})).status,400);
  pass=await call('bob',base+'/entry-token',{});
  db.prepare('UPDATE entry_tokens SET expires_at=? WHERE token=?').run('2020-01-01T00:00:00.000Z',pass.token);
  assert.equal((await call('staff',base+'/checkin',{token:pass.token})).status,400);
  pass=await call('bob',base+'/entry-token',{});
  await call('admin','/api/events',{...config,id,entryCost:150});
  assert.equal((await call('staff',base+'/checkin',{token:pass.token})).status,400);
  pass=await call('bob',base+'/entry-token',{});
  await call('admin',base+'/staff',{userId:'staff',canGrant:false,canRedeem:false,limit:25});
  assert.equal((await call('staff',base+'/checkin',{token:pass.token})).status,403);
  assert.equal((await call('staff',base+'/history')).status,403);
  assert.equal((await call('admin',base+'/checkin',{token:pass.token})).status,200);
  pass=await call('other',base+'/entry-token',{});
  await call('other','/api/wallet/send',{recipientId:'bob',amount:250,requestKey:randomUUID()});
  assert.equal((await call('admin',base+'/checkin',{token:pass.token})).status,400);
  assert.equal(balance('other'),50);
  await call('admin','/api/events',{...config,id,active:false});
  assert.equal((await call('other',base+'/entry-token',{})).status,400);
  assert.equal(total(),initial,'all DGC conserved between users and treasury');
  assert.equal(db.prepare('SELECT COUNT(*) n FROM wallet_transfers').get().n,3);
  assert.equal(db.prepare('SELECT COUNT(*) n FROM event_claims').get().n,4);
  assert.equal(db.prepare("SELECT COUNT(*) n FROM audit_log WHERE event_type='WALLET_TRANSFER'").get().n,3);
  assert.equal(db.prepare("SELECT SUM(amount) n FROM ledger").get().n+db.prepare('SELECT SUM(amount) n FROM house_ledger').get().n,0);
});
